import "./globals.css";
import { Inter } from "next/font/google";
import { ModeToggle } from "@/lib/custom/mode-toggle";
import { ThemeProvider } from "@/lib/custom/theme-provider";
import Topbar from "@/lib/custom/topbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head />
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
        >
           <Topbar />
          {children}
        </ThemeProvider>
        </body>
    </html>
  );
}
